#############################################################################
# Makefile for building: environment
# Generated by qmake (3.1) (Qt 5.9.0)
# Project:  environment.pro
# Template: app
# Command: /home/lfreeman/Qt/5.9/gcc_64/bin/qmake -o Makefile environment.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT5BUILD -DNGL_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -march=native -march=native -g -std=gnu++11 -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/lfreeman/NGL/include -I../common/include -I/home/lfreeman/libigl/include -I/home/lfreeman/eigen -I/usr/local/lib/noise/src -I/home/lfreeman/NGL/include -I/home/lfreeman/Qt/5.9/gcc_64/include -I/home/lfreeman/Qt/5.9/gcc_64/include/QtOpenGL -I/home/lfreeman/Qt/5.9/gcc_64/include/QtWidgets -I/home/lfreeman/Qt/5.9/gcc_64/include/QtGui -I/home/lfreeman/Qt/5.9/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I/home/lfreeman/Qt/5.9/gcc_64/mkspecs/linux-g++
QMAKE         = /home/lfreeman/Qt/5.9/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL_FILE = /home/lfreeman/Qt/5.9/gcc_64/bin/qmake -install qinstall file
QINSTALL_PROGRAM = /home/lfreeman/Qt/5.9/gcc_64/bin/qmake -install qinstall program
QINSTALL_DIR  = /home/lfreeman/Qt/5.9/gcc_64/bin/qmake -install qinstall directory
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = environment1.0.0
DISTDIR = /home/lfreeman/Realtime_Rendering/obj/environment1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/lfreeman/NGL/lib -Wl,-z,origin -Wl,-rpath,\$$ORIGIN/L/home/lfreeman/NGL/lib -Wl,-rpath,/home/lfreeman/NGL/lib -Wl,-rpath,/home/lfreeman/Qt/5.9/gcc_64/lib
LIBS          = $(SUBLIBS) -lXi -ldl -lX11 -lXrandr -lXinerama -lXcursor -lXxf86vm -lglfw3 -lGLEW -lGLU /usr/local/lib//libnoise.a -L/usr/local/lib -L/home/lfreeman/NGL/lib -l NGL -L/home/lfreeman/Qt/5.9/gcc_64/lib -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/envscene.cpp \
		src/camera.cpp \
		src/fixedcamera.cpp \
		src/scene.cpp \
		src/trackballcamera.cpp 
OBJECTS       = obj/main.o \
		obj/envscene.o \
		obj/camera.o \
		obj/fixedcamera.o \
		obj/scene.o \
		obj/trackballcamera.o
DIST          = $OTHER_FILES \
		.qmake.stash \
		common.pri \
		environment.pro src/envscene.h \
		include/camera.h \
		include/fixedcamera.h \
		include/scene.h \
		include/trackballcamera.h src/main.cpp \
		src/envscene.cpp \
		src/camera.cpp \
		src/fixedcamera.cpp \
		src/scene.cpp \
		src/trackballcamera.cpp
QMAKE_TARGET  = environment
DESTDIR       = 
TARGET        = environment


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: environment.pro .qmake.cache /home/lfreeman/Qt/5.9/gcc_64/mkspecs/linux-g++/qmake.conf /home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/spec_pre.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/unix.conf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/linux.conf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/sanitize.conf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/gcc-base.conf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/g++-base.conf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/g++-unix.conf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/qconfig.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/qt_functions.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/qt_config.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/toolchain.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/default_pre.prf \
		/home/lfreeman/NGL/UseNGL.pri \
		common.pri \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/resolve_config.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/default_post.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/warn_on.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/qt.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/resources.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/moc.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/uic.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/unix/thread.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/qmake_use.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/file_copies.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/exceptions.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/yacc.prf \
		/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/lex.prf \
		environment.pro \
		/home/lfreeman/Qt/5.9/gcc_64/lib/libQt5OpenGL.prl \
		/home/lfreeman/Qt/5.9/gcc_64/lib/libQt5Widgets.prl \
		/home/lfreeman/Qt/5.9/gcc_64/lib/libQt5Gui.prl \
		/home/lfreeman/Qt/5.9/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile environment.pro
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/spec_pre.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/unix.conf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/linux.conf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/sanitize.conf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/gcc-base.conf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/g++-base.conf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/common/g++-unix.conf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/qconfig.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/qt_functions.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/qt_config.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/toolchain.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/default_pre.prf:
/home/lfreeman/NGL/UseNGL.pri:
common.pri:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/resolve_config.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/default_post.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/warn_on.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/qt.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/resources.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/moc.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/unix/opengl.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/uic.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/unix/thread.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/qmake_use.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/file_copies.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/testcase_targets.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/exceptions.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/yacc.prf:
/home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/lex.prf:
environment.pro:
/home/lfreeman/Qt/5.9/gcc_64/lib/libQt5OpenGL.prl:
/home/lfreeman/Qt/5.9/gcc_64/lib/libQt5Widgets.prl:
/home/lfreeman/Qt/5.9/gcc_64/lib/libQt5Gui.prl:
/home/lfreeman/Qt/5.9/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile environment.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/envscene.h include/camera.h include/fixedcamera.h include/scene.h include/trackballcamera.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/envscene.cpp src/camera.cpp src/fixedcamera.cpp src/scene.cpp src/trackballcamera.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -msse -msse2 -msse3 -march=native -march=native -g -std=gnu++11 -Wall -W -Wno-unused-parameter -dM -E -o moc_predefs.h /home/lfreeman/Qt/5.9/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

obj/main.o: src/main.cpp src/envscene.h \
		/home/lfreeman/NGL/include/ngl/Obj.h \
		/home/lfreeman/NGL/include/ngl/Types.h \
		/home/lfreeman/NGL/include/ngl/glew.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtOpenGL/QGLContext \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtOpenGL/qgl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qopengl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qtguiglobal.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qflags.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qtgui-config.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qt_windows.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qopengles2ext.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qopenglext.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtWidgets/qwidget.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qwindowdefs.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qobject.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qstring.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qchar.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qlist.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qpair.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qmargins.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpaintdevice.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qrect.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qsize.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qpoint.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpalette.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qcolor.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qrgb.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qrgba64.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qbrush.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qvector.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qmatrix.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpolygon.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qregion.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qdatastream.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qline.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qtransform.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpainterpath.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qimage.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpixelformat.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpixmap.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qsharedpointer.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qhash.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qfont.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qfontmetrics.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qfontinfo.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qcursor.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qkeysequence.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qevent.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qvariant.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qmap.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qdebug.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qtextstream.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qlocale.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qset.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qurl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qurlquery.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qfile.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qfiledevice.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qvector2d.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qtouchdevice.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpaintengine.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpainter.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qtextoption.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpen.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/QSurfaceFormat \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/lfreeman/NGL/include/ngl/Texture.h \
		/home/lfreeman/NGL/include/ngl/Image.h \
		/home/lfreeman/NGL/include/ngl/Colour.h \
		/home/lfreeman/NGL/include/ngl/Vec4.h \
		/home/lfreeman/NGL/include/ngl/Vec2.h \
		/home/lfreeman/NGL/include/ngl/Vec3.h \
		/home/lfreeman/NGL/include/ngl/AbstractMesh.h \
		/home/lfreeman/NGL/include/ngl/BBox.h \
		/home/lfreeman/NGL/include/ngl/AbstractVAO.h \
		/home/lfreeman/NGL/include/ngl/RibExport.h \
		/home/lfreeman/NGL/include/ngl/NGLassert.h \
		include/scene.h \
		include/glinclude.h \
		include/fixedcamera.h \
		include/camera.h \
		include/trackballcamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/envscene.o: src/envscene.cpp src/envscene.h \
		/home/lfreeman/NGL/include/ngl/Obj.h \
		/home/lfreeman/NGL/include/ngl/Types.h \
		/home/lfreeman/NGL/include/ngl/glew.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtOpenGL/QGLContext \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtOpenGL/qgl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qopengl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qtguiglobal.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qflags.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qtgui-config.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qt_windows.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qopengles2ext.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qopenglext.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtWidgets/qwidget.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qwindowdefs.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qobject.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qstring.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qchar.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qlist.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qpair.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qmargins.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpaintdevice.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qrect.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qsize.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qpoint.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpalette.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qcolor.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qrgb.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qrgba64.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qbrush.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qvector.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qmatrix.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpolygon.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qregion.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qdatastream.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qline.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qtransform.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpainterpath.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qimage.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpixelformat.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpixmap.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qsharedpointer.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qhash.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qfont.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qfontmetrics.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qfontinfo.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qcursor.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qkeysequence.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qevent.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qvariant.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qmap.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qdebug.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qtextstream.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qlocale.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qset.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qurl.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qurlquery.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qfile.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtCore/qfiledevice.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qvector2d.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qtouchdevice.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpaintengine.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpainter.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qtextoption.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qpen.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/QSurfaceFormat \
		/home/lfreeman/Qt/5.9/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/lfreeman/NGL/include/ngl/Texture.h \
		/home/lfreeman/NGL/include/ngl/Image.h \
		/home/lfreeman/NGL/include/ngl/Colour.h \
		/home/lfreeman/NGL/include/ngl/Vec4.h \
		/home/lfreeman/NGL/include/ngl/Vec2.h \
		/home/lfreeman/NGL/include/ngl/Vec3.h \
		/home/lfreeman/NGL/include/ngl/AbstractMesh.h \
		/home/lfreeman/NGL/include/ngl/BBox.h \
		/home/lfreeman/NGL/include/ngl/AbstractVAO.h \
		/home/lfreeman/NGL/include/ngl/RibExport.h \
		/home/lfreeman/NGL/include/ngl/NGLassert.h \
		include/scene.h \
		include/glinclude.h \
		/home/lfreeman/NGL/include/ngl/NGLInit.h \
		/home/lfreeman/NGL/include/ngl/Singleton.h \
		/home/lfreeman/NGL/include/ngl/VAOPrimitives.h \
		/home/lfreeman/NGL/include/ngl/ShaderLib.h \
		/home/lfreeman/NGL/include/ngl/Shader.h \
		/home/lfreeman/NGL/include/ngl/ShaderProgram.h \
		/home/lfreeman/NGL/include/ngl/Util.h \
		/home/lfreeman/NGL/include/ngl/Mat3.h \
		/home/lfreeman/NGL/include/ngl/Mat4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/envscene.o src/envscene.cpp

obj/camera.o: src/camera.cpp /home/lfreeman/rendering_examples/common/include/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/camera.o src/camera.cpp

obj/fixedcamera.o: src/fixedcamera.cpp include/fixedcamera.h \
		include/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/fixedcamera.o src/fixedcamera.cpp

obj/scene.o: src/scene.cpp /home/lfreeman/rendering_examples/common/include/scene.h \
		include/glinclude.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/scene.o src/scene.cpp

obj/trackballcamera.o: src/trackballcamera.cpp /home/lfreeman/rendering_examples/common/include/trackballcamera.h \
		/home/lfreeman/rendering_examples/common/include/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/trackballcamera.o src/trackballcamera.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

